proj_dep/pd_app/urls.py
from django.contrib import admin
from django.urls import path, include

import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
    path('__debug__/', include(debug_toolbar.urls)),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj_dep/projects/urls.py
from django.urls import path
from .views import index_view, \
    StaffListView, StaffDetailView, StaffCreateView,\
    StaffUpdateView, StaffDeleteView, \
    ContactFormView, UserCreateView, LoginUserView, LogoutUserView, \
    ProjectListView, ProjectDetailView, ProjectUpdateView, ProjectDeleteView, \
    RoleListView, RoleDetailView, RoleUpdateView, RoleDeleteView


app_name = 'projects'

urlpatterns = [
    path('', index_view, name='index'),
    path('staff/<int:pk>/update/', StaffUpdateView.as_view(), name='update'),
    path('staff/<int:pk>/delete/', StaffDeleteView.as_view(), name='delete'),
    path('staff/<int:pk>/', StaffDetailView.as_view(), name='staff_detail'),
    path('staff/', StaffListView.as_view(), name='staff'),
    path('registry/', UserCreateView.as_view(), name='registry'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('create_staff/', StaffCreateView.as_view(), name='create_staff'),
    path('projects_page/<int:pk>/update/', ProjectUpdateView.as_view(),
         name='update_project'),
    path('projects_page/<int:pk>/delete/', ProjectDeleteView.as_view(),
         name='delete_project'),
    path('projects_page/<int:pk>/', ProjectDetailView.as_view(),
         name='projects_detail'),
    path('projects_page/', ProjectListView.as_view(), name='projects_page'),
    path('roles_page/<int:pk>/update/', RoleUpdateView.as_view(),
         name='update_role'),
    path('roles_page/<int:pk>/delete/', RoleDeleteView.as_view(),
         name='delete_role'),
    path('roles_page/<int:pk>/', RoleDetailView.as_view(), name='roles_detail'),
    path('roles_page/', RoleListView.as_view(), name='roles_page'),
    path('contact_page/', ContactFormView.as_view(), name='contact_page'),
]

proj_dep/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
  </head>

  <div class="container-fluid">
      <ul class="nav">
      <li class="nav-item">
      <a class="nav-link {% if active_page == '1' %} active {% endif %}" href="{% url 'projects:index' %}">Home</a>
      </li>
      <li class="nav-item">
      <a class="nav-link {% if active_page == '1' %} active {% endif %}" href="{% url 'projects:staff' %}">Staff</a>
      </li>
      <li class="nav-item">
      <a class="nav-link {% if active_page == '1' %} active {% endif %}" href="{% url 'projects:projects_page' %}">Projects</a>
      </li>
      <li class="nav-item">
      <a class="nav-link {% if active_page == '1' %} active {% endif %}" href="{% url 'projects:roles_page' %}">Roles</a>
      </li>
      <li class="nav-item">
      <a class="nav-link {% if active_page == '1' %} active {% endif %}" href="{% url 'projects:contact_page' %}">Contact us</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
      <a class="nav-link {% if active_page == '1' %} active {% endif %}" href="{% url 'projects:logout' %}">Log out</a>
      </li>
      {% else %}
      <li class="nav-item">
      <a class="nav-link {% if active_page == '1' %} active {% endif %}" href="{% url 'projects:login' %}">Log in</a>
      </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'projects:registry' %}">Registration</a>
      </li>
      {% endif %}
      <li class="nav-item">
      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Figures</a>
      </li>
      </ul>



      <body>

      {% block content %}
      {% endblock content %}
      </body>

  </div>

</html>