proj_dep/pd_app/urls.py
from django.contrib import admin
from django.urls import path, include

import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls', namespace='projects')),
    path('__debug__/', include(debug_toolbar.urls)),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj_dep/projects/urls.py
from django.urls import path
from .views import index_view, \
    StaffListView, StaffDetailView, StaffCreateView,\
    StaffUpdateView, StaffDeleteView, \
    ContactFormView, UserCreateView, LoginUserView, LogoutUserView, \
    ProjectListView, ProjectDetailView, ProjectUpdateView, ProjectDeleteView, \
    RoleListView, RoleDetailView, RoleUpdateView, RoleDeleteView


app_name = 'projects'

urlpatterns = [
    path('', index_view, name='index'),
    path('staff/<int:pk>/update/', StaffUpdateView.as_view(), name='update'),
    path('staff/<int:pk>/delete/', StaffDeleteView.as_view(), name='delete'),
    path('staff/<int:pk>/', StaffDetailView.as_view(), name='staff_detail'),
    path('staff/', StaffListView.as_view(), name='staff'),
    path('registry/', UserCreateView.as_view(), name='registry'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('create_staff/', StaffCreateView.as_view(), name='create_staff'),
    path('projects_page/<int:pk>/update/', ProjectUpdateView.as_view(),
         name='update_project'),
    path('projects_page/<int:pk>/delete/', ProjectDeleteView.as_view(),
         name='delete_project'),
    path('projects_page/<int:pk>/', ProjectDetailView.as_view(),
         name='projects_detail'),
    path('projects_page/', ProjectListView.as_view(), name='projects_page'),
    path('roles_page/<int:pk>/update/', RoleUpdateView.as_view(),
         name='update_role'),
    path('roles_page/<int:pk>/delete/', RoleDeleteView.as_view(),
         name='delete_role'),
    path('roles_page/<int:pk>/', RoleDetailView.as_view(), name='roles_detail'),
    path('roles_page/', RoleListView.as_view(), name='roles_page'),
    path('contact_page/', ContactFormView.as_view(), name='contact_page'),
]

proj_dep/projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Staff(models.Model):
    name = models.CharField(max_length=64, default='no-name')
    surname = models.CharField(max_length=64, default='no-surname')
    sl_position = models.ManyToManyField("StaffListPosition", blank=True)
    salary = models.DecimalField(max_digits=9, decimal_places=2,
                                 default=150_000.00)
    direct = models.ManyToManyField("Direction", blank=True)
    serts = models.ManyToManyField("Sertificate", blank=True)
    is_staff = models.BooleanField(default=False)
    image = models.ImageField(upload_to='staff', blank=True, null=True)
    profile = models.FileField(upload_to='staff/profiles', blank=True,
                               null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                             blank=True)

    def __str__(self):
        return f"{self.name} {self.surname} " \
               f"(id# {self.id})"


# class StaffImage(models.Model):
#     image = models.ImageField(upload_to='staff')
#     staff = models.ForeignKey(Staff, on_delete=models.CASCADE)


class StaffListPosition(models.Model):
    name = models.CharField(max_length=128, default='no-position')

    def __str__(self):
        return self.name


class Direction(models.Model):
    name = models.CharField(max_length=64, default='no-direction')

    def __str__(self):
        return self.name


class Sertificate(models.Model):
    name = models.CharField(max_length=256, null=False, blank=False)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=256, null=False, blank=False)
    direction = models.ManyToManyField(Direction, blank=True)
    description = models.TextField(null=True)

    def __str__(self):
        return self.name

    def project_resource_count(self):

        res = []
        for s in Stage.objects.filter(proj__id=self.id):
            for r in Role.objects.filter(stages__id=s.id):
                res.append(r.staff.id)
        return len(list(set(res)))


class Stage(models.Model):
    name = models.CharField(max_length=256, null=False, blank=False)
    proj = models.ForeignKey(Project, on_delete=models.CASCADE, null=False,
                             blank=False)
    start_plan = models.DateField(null=True, blank=True)
    start_fact = models.DateField(null=True, blank=True)
    end_plan = models.DateField(null=True, blank=True)
    end_fact = models.DateField(null=True, blank=True)
    exp_plan = models.DecimalField(max_digits=11, decimal_places=2,
                                   default=1.00)
    exp_fact = models.DecimalField(max_digits=11, decimal_places=2,
                                   default=1.00)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} of {self.proj}"


class Role(models.Model):
    name = models.CharField(max_length=64, null=False, blank=False)
    proj = models.ForeignKey(Project, on_delete=models.CASCADE, null=False,
                             blank=False)
    stages = models.ManyToManyField(Stage, blank=True)
    staff = models.ForeignKey(Staff, on_delete=models.SET_NULL, blank=True,
                              null=True)

    def __str__(self):
        return f"{self.name} in {self.proj}"

proj_dep/projects/forms.py
from django import forms
from .models import Staff, Project,Role
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class ContactForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs=
                                                    {'class': 'form-control'}))
    subject = forms.CharField(widget=forms.TextInput(attrs=
                                                     {'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs=
                                                    {'class': 'form-control'}))

    def form_valid(self, form):
        return super().form_valid(form)


class StaffForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Staff
        exclude = ('user',)


class ProjectForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    description = forms.TextInput()

    class Meta:
        model = Project
        exclude = ('user',)

class RoleForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    class Meta:
        model = Role
        exclude = ('user',)

class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your password',
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {'username' : forms.TextInput(attrs={
            'placeholder': 'John Gault',
            'class':
                'col-md-12form-control'}),
                   'email' : forms.EmailInput(attrs={
                       'placeholder': 'your@mail.com',
                       'class': 'col-md-12form-control'
                   }),
                   }


class LoginForm(AuthenticationForm):
    class Meta:
        fields = '__all__'

proj_dep/projects/views.py
from django.shortcuts import render
from .models import Staff, StaffListPosition, Direction, Sertificate
from .models import Project, Stage, Role
# from celery import current_app
from django.views.generic import ListView, DetailView, UpdateView, \
    CreateView, FormView, DeleteView
from .forms import ContactForm, StaffForm, RegistrationForm, LoginForm, ProjectForm, RoleForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class AdminOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        # просто сформулировать условие выдачи прав
        # return self.request.user.email.endswith('@example.com')
        return self.request.user.is_superuser


class StaffOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

# - - - - - - - - - - - - - - - - - - - - - - - - -

def index_view(request):
    context = {}
    context['staff_units'] = Role.objects.all().count()
    context['proj_units'] = Project.objects.all().count()
    context['dir_units'] = Direction.objects.all().count()
    context['sl_units'] = StaffListPosition.objects.all().count()
    context['sert_units'] = Sertificate.objects.all().count()
    context['active_page'] = '1'
    return render(request, 'projects/index.html', context)

# - - - - - - - - - - - - - - - - - - - - - - - - -


class StaffListView(ListView):
    model = Staff # Модель, которую нужно вывести в список
    template_name = 'projects/staff.html' # в какой шаблон выведем данные

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = '1'
        return context


class StaffDetailView(LoginRequiredMixin, DetailView):
    model = Staff
    template_name = 'projects/staff_detail.html'


class StaffCreateView(StaffOnlyMixin, CreateView):
    model = Staff
    template_name = 'projects/edit_create_staff.html'
    success_url = '/'
    form_class = StaffForm

    def form_valid(self, form):
        user = self.request.user # мы т.к. в форме создания змеи скрывали пользователя
        form.instance.user = user # прописываем его из инстанса формы
        return super().form_valid(form) # сохраняем форму


class StaffUpdateView(StaffOnlyMixin, UpdateView):
    model = Staff
    template_name = 'projects/edit_create_staff.html'
    success_url = '/'
    form_class = StaffForm


class StaffDeleteView(AdminOnlyMixin, DeleteView):
    model = Staff
    template_name = 'projects/delete_confirm_staff.html'
    success_url = '/'

# - - - - - - - - - - - - - - - - - - - - - - - - -

class ProjectListView(ListView):
    model = Project # Модель, которую нужно вывести в список
    template_name = 'projects/projects_page.html' # в какой шаблон выведем данные

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = '1'
        return context


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'projects/projects_detail.html'


class ProjectCreateView(StaffOnlyMixin, CreateView):
    model = Project
    template_name = 'projects/edit_create_project.html'
    success_url = '/projects/'
    # fields = '__all__' # возьмем все поля
    # fields = ('name',) # перечислим нужные поля
    # исключить ненужные поля можно в формах
    form_class = ProjectForm

    def form_valid(self, form):
        user = self.request.user # мы т.к. в форме создания змеи скрывали пользователя
        form.instance.user = user # прописываем его из инстанса формы
        return super().form_valid(form) # сохраняем форму


class ProjectUpdateView(StaffOnlyMixin, UpdateView):
    model = Project
    template_name = 'projects/edit_create_project.html'
    success_url = '/'
    form_class = ProjectForm


class ProjectDeleteView(AdminOnlyMixin, DeleteView):
    model = Project
    template_name = 'projects/delete_confirm_project.html'
    success_url = '/'

# - - - - - - - - - - - - - - - - - - - - - - - - -

class RoleListView(ListView):
    model = Role # Модель, которую нужно вывести в список
    template_name = 'projects/roles_page.html' # в какой шаблон выведем данные

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = '1'
        return context


class RoleDetailView(LoginRequiredMixin, DetailView):
    model = Role
    template_name = 'projects/roles_detail.html'


class RoleCreateView(StaffOnlyMixin, CreateView):
    model = Role
    template_name = 'projects/edit_create_role.html'
    success_url = '/roles_page/'
    form_class = RoleForm

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super().form_valid(form)

class RoleUpdateView(StaffOnlyMixin, UpdateView):
    model = Role
    template_name = 'projects/edit_create_role.html'
    success_url = '/roles_page/'
    # fields = '__all__' # возьмем все поля
    form_class = RoleForm

class RoleDeleteView(AdminOnlyMixin, DeleteView):
    model = Role
    template_name = 'projects/delete_confirm_role.html'
    success_url = '/roles_page/'

# - - - - - - - - - - - - - - - - - - - - - - - - -

class ContactFormView(LoginRequiredMixin, FormView):
    template_name = "projects/contact_page.html"
    form_class = ContactForm
    success_url = '/'

# - - - - - - - - - - - - - - - - - - - - - - - - -


class LoginUserView(LoginView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'projects/login.html'


class LogoutUserView(LogoutView):
    pass

# - - - - - - - - - - - - - - - - - - - - - - - - -


class UserCreateView(CreateView):
    model = User
    form_class = RegistrationForm
    success_url = '/login/'
    template_name = 'projects/register.html'

proj_dep/projects/templates/projects/contact_page.html
{% extends "base.html" %}

{% block title %}
    ..
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="alert alert-info" role="alert">
        <h1> Contact us </h1>
    </div>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Send</button>
        </form>
</div>
{% endblock %}

proj_dep/projects/templates/projects/delete_confirm_project.html
{% extends "base.html" %}

{% block title %}
    {{object.name}}' delete
{% endblock %}

{% block content %}
    <div class="alert alert-info" role="alert">
        <h1> Delete project </h1>
    </div>
    Are you shure to delete {{object.name}}?


    <hr>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger">Yes, delete {{object.name}}</button>
    </form>


{% endblock %}

proj_dep/projects/templates/projects/delete_confirm_role.html
{% extends "base.html" %}

{% block title %}
    {{object.name}}' delete
{% endblock %}

{% block content %}
    <div class="alert alert-info" role="alert">
        <h1> Delete Role </h1>
    </div>
    Are you shure to delete {{object.name}}?


    <hr>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger">Yes, delete {{object.name}}</button>
    </form>


{% endblock %}

proj_dep/projects/templates/projects/delete_confirm_staff.html
{% extends "base.html" %}

{% block title %}
    {{object.name}}' delete
{% endblock %}

{% block content %}
    <div class="alert alert-info" role="alert">
        <h1> Fair employee </h1>
    </div>
    Are you shure to fair {{object.name}}?


    <hr>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger">Yes, fair {{object.name}}</button>
    </form>


{% endblock %}

proj_dep/projects/templates/projects/edit_create_role.html
{% extends "base.html" %}

{% block title %}
    Edit
{% endblock %}

{% block content %}
    <div class="alert alert-info" role="alert">
        <h1> Edit role </h1>
    </div>
<div class="container-fluid">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

{% endblock %}

proj_dep/projects/templates/projects/edit_create_staff.html
{% extends "base.html" %}

{% block title %}
    Add
{% endblock %}

{% block content %}
    <div class="alert alert-info" role="alert">
        <h1> Add an employee </h1>
    </div>

<div class="container-fluid">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

proj_dep/projects/templates/projects/index.html
{% extends "base.html" %}

{% block title %}
    Start page
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="alert alert-info" role="alert">
        <h1> Main information </h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-4">
                <h4><b>Team:</b> {{ staff_units }} professionals</h4>
                <h4><b>Projects:</b> {{ proj_units }}</h4>
                <h4><b>Directions:</b> {{ dir_units }}</h4>
                <h4><b>State list positions:</b> {{ sl_units }}</h4>
                <h4><b>Sertificates:</b> {{ sert_units }}</h4>
            </div>
            <div class="col-8">
                <iframe class="embed-responsive-16by9"
                src="https://www.youtube.com/embed/qrwlk7_GF9g"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
                </iframe>
            </div>
        </div>

    </div>
    <br>

</div>
{% endblock %}

proj_dep/projects/templates/projects/login.html
{% extends "base.html" %}

{% block title %}
    Log in
{% endblock %}

{% block content %}
    <div class="alert alert-info" role="alert">
        <h1> Log in </h1>
    </div>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Log in</button>
    </form>
{% endblock %}

proj_dep/projects/templates/projects/projects_detail.html
{% extends "base.html" %}

{% block title %}
    Project {{ object.pk }}
{% endblock %}

{% block content %}

<div class="container-fluid d-done">
    <div class="alert alert-info" role="alert">
        <h1> Project {{ object.pk }} </h1>
    </div>

    <div class="container">
        <h4>Project {{ object.name }}</h4>
        <i>Project {{ object.description }}</i>
    </div>

    <hr>
    <a href="{% url 'projects:update_project' pk=object.pk %}" class="btn btn-primary">Edit {{object.name}}</a>
    <a href="{% url 'projects:delete_project' pk=object.pk %}" class="btn btn-danger">Delete {{object.name}}</a>

</div>

{% endblock %}

proj_dep/projects/templates/projects/register.html
{% extends "base.html" %}

{% block title %}
    Registry
{% endblock %}


{% block content %}
    <div class="alert alert-info" role="alert">
        <h1> Registration </h1>
    </div>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Log up</button>
    </form>
{% endblock %}

proj_dep/projects/templates/projects/roles_detail.html
{% extends "base.html" %}

{% block title %}
    Role {{ object.pk }}
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="alert alert-info" role="alert">
        <h1> Role {{ object.pk }} </h1>
    </div>

    <div class="container">
        <h4>Role {{ object.pk }}</h4>
    </div>

    <hr>
    <a href="{% url 'projects:update_role' pk=object.pk %}" class="btn btn-primary">Edit {{object.name}}</a>
    <a href="{% url 'projects:delete_role' pk=object.pk %}" class="btn btn-danger">Delete {{object.name}}</a>

</div>
{% endblock %}

proj_dep/projects/templates/projects/roles_page.html
{% extends "base.html" %}

{% block title %}
    Roles
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="alert alert-info" role="alert">
        <h1> Roles </h1>
    </div>

    <div class="container">
        <h3> All roles </h3>
        <div class="row">
            <div class="col col-12 col-md-8 col-lg-6 col-xl-4">
                <ul class="list-group">
                    {% for unit in object_list %}
                    <li class="list-group-item"> {{ unit.name }} {{ unit.proj }}
                        <br>{{ unit.staff }} <br>
                        <a href="{% url 'projects:roles_detail' unit.pk %}">more...
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

proj_dep/projects/templates/projects/staff.html
{% extends "base.html" %}

{% block title %}
    Staff
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="alert alert-info" role="alert">
        <h1> Main </h1>
    </div>

    <div class="container">
        <h3> All members </h3>
        <div class="row">
            <div class="col col-12 col-md-8 col-lg-6 col-xl-4">
                <ul class="list-group">
                    {% for unit in object_list %}
                    <li class="list-group-item">
                        {% if unit.image %}
                            <img class="img rounded-circle" width="50px"
                                 height="50px" src="{{ unit.image.url }}" alt="employee">
                        {% else %}
                            <img class="img rounded-circle" width="50px"
                                 height="50px" src="media/staff/staff_default.png" alt="employee">
                        {% endif %}
                        <a href="{% url 'projects:staff_detail' unit.pk %}">{{ unit.name }}</a>

                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% if user.is_authenticated %}
        <br>
        <a href="{% url 'projects:create_staff' %}"
           class="btn btn-primary">Hair a new employee</a>
        {% else %}
        {% endif %}
    </div>
</div>
{% endblock %}

proj_dep/projects/templates/projects/staff_detail.html
{% extends "base.html" %}

{% block title %}
    {{ object.name }}
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="alert alert-info" role="alert">
        <h1> Personal page </h1>
    </div>
    <br>
    <h3><b>NAME:</b> {{ object.name }} {{ object.surname }}</h3>
        {% if object.image %}
        <img class="img" width="150px"
        height="150px" src="{{ object.image.url }}" alt="employee">
        {% endif %}
    {% if object.is_staff == True %}
    <h3><b>STAFF LIST POSITION:</b>
        <ul>
        {% for position in object.sl_position.all %}
            <li> {{ position }}</li>
        {% endfor %}
        </ul>
        </h3>
    {% else %}
    <h3>freelance </h3>
    {% endif %}

    <h3><b>SALARY:</b> {{ object.salary }} RUB</h3>
    <h3><b>DIRECTIONS:</b>
        <ul>
        {% for direction in object.direct.all %}
        <li> {{ direction }}</li>
        {% endfor %}
        </ul>
    </h3>
        <h3><b>SERTIFICATES:</b>
        <ul>
            {% for sert in object.serts.all %}
            <li>{{sert}}</li>
            {% endfor %}
        </ul>
        </h3>

    {% if object.profile %}
    <h3><b>PROFILE:</b>
    <a href="{{ unit.profile.url }}" download>download</a>
    {% endif %}

    <hr>
    <a href="{% url 'projects:update' pk=object.pk %}" class="btn btn-primary">Edit {{object.name}}</a>
    <a href="{% url 'projects:delete' pk=object.pk %}" class="btn btn-danger">Delete {{object.name}}</a>

</div>
{% endblock %}